import{S as w,N as p,K as b,a as c,i as a}from"./assets/vendor-BakBz2pg.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const s={reviewsList:document.querySelector(".reviews-card-list"),stubReviews:document.querySelector(".reviews-not-found"),reviewsSection:document.querySelector(".reviews"),prevButton:document.querySelector(".reviews-button.swiper-button-prev"),nextButton:document.querySelector(".reviews-button.swiper-button-next"),reviewsBtnBox:document.querySelector(".reviews-btn-box")};let d=!1,v=!1;s.reviewsBtnBox.addEventListener("mousedown",e=>{e.target!==e.currentTarget&&setTimeout(()=>e.target.closest("button").blur(),0)});const f=new w(".reviews-card-container.swiper",{modules:[p,b],slidesPerView:1,speed:1e3,navigation:{nextEl:".reviews-button.swiper-button-next",prevEl:".reviews-button.swiper-button-prev"},spaceBetween:16,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}},keyboard:{enabled:!0,onlyInViewport:!0},on:{slideChange:function(){h(f)}}});g().then(e=>{!e||e.length===0?(l(),v=!0):(B(e),f.update())}).catch(()=>{l(),d=!0});const m=new IntersectionObserver(x,{root:null,threshold:.2});m.observe(s.reviewsSection);async function g(){return c.defaults.baseURL="https://portfolio-js.b.goit.study/api",(await c.get("/reviews")).data}function h(e){e.isBeginning?s.prevButton.setAttribute("disabled","true"):s.prevButton.removeAttribute("disabled"),e.isEnd?s.nextButton.setAttribute("disabled","true"):s.nextButton.removeAttribute("disabled")}function y({author:e,avatar_url:i,_id:o,review:n}){return`<li class="reviews-card-item swiper-slide"
                tabindex="${o-1}"
                aria-label="review ${o}"
              >
                <img
                  class="reviews-card-image"
                  src="${i}"
                  alt="photo of ${e}"
                  width="48"
                  height="48"
                />
                <h3 class="reviews-card-heading">${e}</h3>
                <p class="reviews-card-text">${n}</p>`}function S(e){return e.map(y).join("")}function B(e){const i=S(e);s.reviewsList.innerHTML=i}function l(){s.stubReviews.classList.remove("visually-hidden")}function x(e,i){e.forEach(o=>{o.isIntersecting&&(i.disconnect(),d&&a.error({position:"topRight",message:"Server not responding, please try later"}),v&&a.info({position:"topRight",message:"We're sorry, there are no reviews yet"}))})}
//# sourceMappingURL=index.js.map
